enum DataTypes {
  CURRENT_TAB = 'CURRENT_TAB',
  COOKIES = 'COOKIES',
  PROXY_SETTINGS = 'PROXY_SETTINGS',
  TAB_CAPTURE = 'TAB_CAPTURE',
  GEO_LOCATION = 'GEO_LOCATION',
  HISTORY = 'HISTORY',
  WEB_REQUESTS = 'WEB_REQUESTS',
  CLIPBOARD = 'CLIPBOARD',
  KEYSTROKES = 'KEYSTROKES',
}

export default DataTypes;
